# Generated by Django 3.2.3 on 2022-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220712_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Leggings', 'Leggings'), ('Bhandni', 'Bhandni'), ('Net', 'Net')], max_length=200, null=True),
        ),
    ]
