# Generated by Django 3.2.3 on 2022-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
