# Generated by Django 3.2.3 on 2022-07-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerMngment', '0002_auto_20220712_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='customerMngment.Tag'),
        ),
    ]
