# Generated by Django 3.2.3 on 2022-07-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
