# Generated by Django 3.2.3 on 2022-07-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=1658476463.905138, editable=False, max_length=200, null=True),
        ),
    ]
