# Generated by Django 3.2.3 on 2022-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=1658769964.865862, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Leggings', 'Leggings'), ('Bhandni', 'Bhandni'), ('Net', 'Net'), ('Ajrak', 'Ajrak')], max_length=200, null=True),
        ),
    ]
