# Generated by Django 3.2.3 on 2022-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_auto_20220725_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=1658825481.366656, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Leggings', 'Leggings'), ('Bhandni', 'Bhandni'), ('Net', 'Net'), ('Ajrak', 'Ajrak'), ('Plaso', 'Plaso')], max_length=200, null=True),
        ),
    ]
